### ISSUE TITLE
What on a search head would cause this error in multiple ucc-built add-ons?

### ISSUE THREAD

**Issue by rosskarchner** [splunk/addonfactory-ucc-library#239]
I'm troubleshooting a UCC app that where the configuration screen returns a 500 error, with the below error in the splunkd log. On a hunch, I tried a different app built with UCC (the official databricks add-on) and it behaves the same way. Do you have any ideas about what we should be looking at to resolve this error?

```
09-14-2023 08:07:06.458 -0400 ERROR AdminManagerExternal [1499431 TcpChannelThread] - Unexpected error "<class 'splunktaucclib.rest_handler.error.RestError'>" from python handler: "REST Error [500]: Internal Server Error -- Migrating failed. Traceback (most recent call last):\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 710, in urlopen\n chunked=chunked,\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 449, in _make_request\n six.raise_from(e, None)\n File "<string>", line 3, in raise_from\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 444, in _make_request\n httplib_response = conn.getresponse()\n File "/opt/splunk/lib/python3.7/http/client.py", line 1373, in getresponse\n response.begin()\n File "/opt/splunk/lib/python3.7/http/client.py", line 319, in begin\n version, status, reason = self._read_status()\n File "/opt/splunk/lib/python3.7/http/client.py", line 280, in _read_status\n line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n File "/opt/splunk/lib/python3.7/socket.py", line 589, in readinto\n return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/requests/adapters.py", line 449, in send\n timeout=timeout\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 786, in urlopen\n method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/util/retry.py", line 550, in increment\n raise six.reraise(type(error), error, _stacktrace)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/packages/six.py", line 769, in reraise\n raise value.with_traceback(tb)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 710, in urlopen\n chunked=chunked,\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 449, in _make_request\n six.raise_from(e, None)\n File "<string>", line 3, in raise_from\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/urllib3/connectionpool.py", line 444, in _make_request\n httplib_response = conn.getresponse()\n File "/opt/splunk/lib/python3.7/http/client.py", line 1373, in getresponse\n response.begin()\n File "/opt/splunk/lib/python3.7/http/client.py", line 319, in begin\n version, status, reason = self._read_status()\n File "/opt/splunk/lib/python3.7/http/client.py", line 280, in _read_status\n line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n File "/opt/splunk/lib/python3.7/socket.py", line 589, in readinto\n return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunk_aoblib/rest_migration.py", line 19, in handle\n return func(*args, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunk_aoblib/rest_migration.py", line 68, in _migrate\n self._migrate_conf()\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunk_aoblib/rest_migration.py", line 89, in _migrate_conf\n conf_file, stanzas = self._load_conf(conf_file_name)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunk_aoblib/rest_migration.py", line 175, in _load_conf\n if conf_file_name not in self.client.confs:\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/client.py", line 1718, in __contains__\n response = self.get(key)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/client.py", line 1668, in get\n return super(Collection, self).get(name, owner, app, sharing, **query)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/client.py", line 766, in get\n **query)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/binding.py", line 290, in wrapper\n return request_fun(self, *args, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/binding.py", line 71, in new_f\n val = f(*args, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/binding.py", line 686, in get\n response = self.http.get(path, all_headers, **query)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/binding.py", line 1199, in get\n return self.request(url, { 'method': "GET", 'headers': headers })\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/splunklib/binding.py", line 1259, in request\n response = self.handler(url, message, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/solnlib/splunk_rest_client.py", line 147, in request\n **kwargs,\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/requests/api.py", line 61, in request\n return session.request(method=method, url=url, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/requests/sessions.py", line 542, in request\n resp = self.send(prep, **send_kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/requests/sessions.py", line 655, in send\n r = adapter.send(request, **kwargs)\n File "/opt/splunk/etc/apps/conneQt/bin/conneqt/aob_py3/requests/adapters.py", line 498, in send\n raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n". See splunkd.log/python.log for more details.
```

**Comment by artemrys** [comment]
Hey @rosskarchner 
Thanks for letting us know
I checked the [Databricks add-on](https://splunkbase.splunk.com/app/5416) and it seems it is built with AoB (Add-on Builder). I successfully installed on my local Splunk instance and configuration page seems to be working fine.
Can you please share more details how could I reproduce the issue?

**Comment by rosskarchner** [comment]
That's the thing-- I was trying to get ideas for what configuration problem/mistake could cause that issue, in order to be able to reproduce it.

And I found it! It looks like it was this lovely issue, caused by using "True" instead of "true" in server.conf

https://community.splunk.com/t5/Getting-Data-In/How-to-resolve-ServiceNow-TA-Error-quot-Failed-to-load-current/m-p/633659/highlight/true#M108485

I asked our splunk admin to take a look, and sure enough, he changed True to true, and after an overnight reboot I can now configure the add-ons in question.

**Comment by artemrys** [comment]
@rosskarchner seems the issue is resolved, should I close this issue?

**Comment by rosskarchner** [comment]
Yeah, go ahead (but hope someday you consider making the error messages a little less opaque)

**Comment by artemrys** [comment]
Yeah, let me see if we have a Jira for that, I'll see if it is possible to prioritise it.
